wearefuturegov/beacon

- Gemfile
- Gemfile.lock
- app/models/contact.rb
- db/migrate/20200328094815_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
- db/migrate/20200328094816_add_missing_unique_indices.acts_as_taggable_on_engine.rb
- db/migrate/20200328094817_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
- db/migrate/20200328094818_add_missing_taggable_index.acts_as_taggable_on_engine.rb
- db/migrate/20200328094820_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
- db/schema.rb
Add tagging capabilities to the Contact model.
> Make contacts taggable

- app/models/contact.rb
- app/models/note.rb
- db/migrate/20200329100626_create_notes.rb
- db/schema.rb
- spec/factories/notes.rb
- spec/models/contact_spec.rb
- spec/models/note_spec.rb
> Add notes / comment model

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/contacts_controller.rb
- app/controllers/my_tasks_controller.rb
- app/controllers/tasks_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/helpers/tasks_helper.rb
- app/models/contact.rb
- app/models/task.rb
- app/models/user.rb
- app/views/application/_tasks_table.html.erb
- app/views/contacts/index.html.erb
- app/views/layouts/application.html.erb
- app/views/my_tasks/index.html.erb
- app/views/tasks/index.html.erb
- app/views/users/index.html.erb
- config/initializers/paper_trail.rb
- config/routes.rb
- db/migrate/20200330064918_create_versions.rb
- db/migrate/20200330064919_add_object_changes_to_versions.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/contacts.rb
- spec/models/contact_spec.rb
- spec/models/task_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- add tasks and my-tasks views;
- add pagiantion to tasks, contacts, users;
- add more seed data;
> Tasks index

- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/views/contacts/_form.html.erb
- db/migrate/20200331094721_add_additional_info_to_contact.rb
- db/schema.rb
- spec/factories/contacts.rb
> add additional info and priority to contact edit screen

- app/controllers/my_tasks_controller.rb
- app/views/my_tasks/index.html.erb
- app/views/tasks/index.html.erb
> amend the my tasks view

- app/controllers/concerns/params_concern.rb
- app/controllers/my_needs_controller.rb
- app/controllers/needs_controller.rb
- app/javascript/packs/datatables.js
- app/views/my_needs/index.html.erb
- app/views/needs/index.html.erb
- app/views/shared/_needs_table.html.erb
> add filters to top bar and refactor filter logic

- app/javascript/packs/datatables.js
- app/views/shared/_needs_table.html.erb
> comple bookmarkable filtering

- README.md
- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
- app/views/layouts/login.html.erb
- config/councils.yml
- config/initializers/passwordless.rb
`COUNCIL` need to be set 'camden' on heroku
>  make concil data configurable by env variable

- app/views/contacts/show.html.erb
Its not quite what the figma design is, but at least it no longer shows
placeholders and is more consistent with the design I implemented in #46. This shouldn't cause any merge conflicts with #46 or anything 🤞
> Improve show contact page design

- app/assets/stylesheets/header.scss
- app/controllers/application_controller.rb
- app/views/contacts/show_needs.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/login.html.erb
- app/views/needs/index.html.erb
- app/views/shared/_head.html.erb
- config/councils.yml
This is done on #47's branch, and the PR has that branch as the base. You can change the base of the PR by modifying it. See commit logs for details.
> Misc ui fixes

- app/controllers/needs_controller.rb
- app/helpers/needs_helper.rb
- app/views/needs/index.html.erb
> add page size to needs table

- Gemfile
- Gemfile.lock
- app/controllers/needs_controller.rb
- app/helpers/needs_helper.rb
- app/models/need.rb
- app/views/needs/index.html.erb
- app/views/shared/_needs_table.html.erb
- config/routes.rb
> Add export csv link

- app/views/users/index.html.erb
We dont need notice handling in action views, because we already have it in ` app/views/layouts/application.html.erb`.
> Fix inviting a new user shows success flash twice

- app/assets/stylesheets/filters.scss
- app/controllers/needs_controller.rb
- app/helpers/needs_helper.rb
- app/javascript/packs/filters.js
- app/views/needs/_filters.html.erb
- app/views/shared/_side-nav.html.erb
Fix filtering of needs:
- Re-enable/fx `assigned to` filter
- Update nav bar's 'assigned to me' link to use `current_user`
- Fix category filter
- Nav bar link highlights should indicate current page
Trello: https://trello.com/c/k9ABWrSy/293-fix-filtering-of-needs
> Fix filtering of needs

- app/controllers/triage_controller.rb
- spec/controllers/triage_controller_spec.rb
Steps to reproduce:
1) Open a contact
2) Click Triage call
3) Remove first name
4) Click save
> fix bug with contact page validation

- config/initializers/passwordless.rb
to get around spam filter limits
> allow token reuse

- app/controllers/contacts_controller.rb
- app/controllers/triage_controller.rb
- app/models/need.rb
- app/views/contacts/_extra_questions.html.erb
- app/views/shared/_profile-accordion.html.erb
- db/migrate/20200415112651_add_has_covid_symptoms_to_contact.rb
- db/migrate/20200415112651_add_has_covid_to_contact.rb
- db/schema.rb
- features/step_definitions/person_steps.rb
- features/update_resident.feature
Added the Covid19 question, amended the csv export and added a e2e test
> add fields to needs export

- app/models/need.rb
- app/views/triage/_groceries_and_cooked_meals.html.erb
> add radio for any dietary requirement question back

- app/models/contact.rb
- app/views/shared/_profile-accordion.html.erb
- db/migrate/20200415172718_remove_healthintent_import_data_from_contacts.rb
- db/schema.rb
- spec/factories/contacts.rb
The latest camden data does not include this anymore
> Remove healthintent data

- spec/factories/contacts.rb
- spec/factories/needs.rb
contacts.has_covid_symptoms, needs.food_priority, and needs.food_service_type
> Add seeds for new fields

- app/controllers/contacts_controller.rb
- app/helpers/needs_helper.rb
- app/views/contacts/_enquiry.html.erb
- app/views/contacts/index.html.erb
- app/views/contacts/new.html.erb
- app/views/contacts/show.html.erb
- app/views/users/_form.html.erb
- config/routes.rb
- db/migrate/20200422121348_add_channel_to_contacts.rb
- db/migrate/20200422121355_add_enquiry_referral_to_contacts.rb
- db/migrate/20200422121439_add_enquiry_message_to_contacts.rb
- db/schema.rb
- features/new_enquiry.feature
- features/step_definitions/edit_need_steps.rb
- features/step_definitions/new_enquiry_steps.rb
- features/step_definitions/person_steps.rb
- spec/factories/needs.rb
> 358 14 inbound enquiry capture 2 data retention

- app/javascript/packs/application.js
- app/javascript/packs/enquiry-common.js
- app/javascript/packs/popup.js
Background:
https://trello.com/c/TGmpxL1m/359-12-quick-capture-referral
I also had the popup code inside another js file.
Solution: 
Extracted popup logic into its own file. This way, every developer can use it in his own views.
> 12 quick capture referral popup refinement

- lib/tasks/contact_channel.rake
Task: https://trello.com/c/jRTq9kV7/395-migration-script-for-contactchannel
```
i-have-i-need$ bundle exec rake contact_channel:update_contacts_channel
```
> Create migration script for contact.channel

- Gemfile.lock
- app/assets/stylesheets/bulk-actions.scss
- app/assets/stylesheets/forms.scss
- app/controllers/needs_controller.rb
- app/javascript/packs/bulk-actions.js
- app/models/need.rb
- app/policies/need_policy.rb
- app/views/needs/_bulk-actions.erb
- app/views/needs/_filters.html.erb
- app/views/needs/_need-actions.html.erb
- app/views/needs/index.html.erb
- config/routes.rb
- features/step_definitions/edit_need_steps.rb
Supposed to be looking like this:
Actual:
Also tested on IE11
> 375 10 allow assigning a need to a role pt2

- README.md
- app.json
- app/helpers/needs_helper.rb
- app/views/contacts/_form_fields.html.erb
- app/views/contacts/index.html.erb
- app/views/needs/index.html.erb
- app/views/shared/_vulnerable-banner.html.erb
- features/add_needs.feature
- features/step_definitions/person_steps.rb
Change all labels from 'vulnerable' to 'shielding' throughout application
Task: https://trello.com/c/4nC96Lpy/405-misc-rename-vulnerable-to-shielding-throughout-application
> Change all labels from 'vulnerable' to 'shielding'

- .rubocop.yml
- app/controllers/assessments_controller.rb
- app/controllers/needs_controller.rb
- app/javascript/packs/bulk-actions.js
- app/models/need.rb
- app/views/assessments/new.html.erb
- app/views/needs/_bulk-actions.erb
- app/views/needs/_filters.html.erb
- app/views/needs/_need-actions.html.erb
- features/step_definitions/edit_support_actions_steps.rb
- spec/controllers/needs_controller_spec.rb
On the show need page, bulk assignment, and filters
This will have broken some tests, as expected, but thought I'd share my approach before diving into fixing tests.
> Combine the 'assign to user' and 'assign to team' dropdowns

- lib/tasks/contact_channel.rake
- lib/tasks/needs_status.rake
- lib/tasks/upgrade.rake
- lib/tasks/users_roles.rake
This lets us run `rake upgrade:v1_1_0` and it will run each task in the namespace. Just an idea; if there's another convention out there we can use that instead.
> Namespace data upgrade rake tasks

- lib/tasks/contact_channel.rake
Per Siobhan at https://docs.google.com/document/d/1850ltRG7T7vJxczEHoHaSxPoLwnANwePeqb3rNS4A_o/edit?disco=AAAAGdjTSto
> Change data task to set channel to Shielded Cohort instead of imported

- app/views/shared/_side-nav.html.erb
- features/step_definitions/user_roles_steps.rb
Fixes "My dashboard" link and indents the nested navbar links. Also fixes the `Un-started` -> `Unstarted`
> Navbar nesting & fix my dashboard link

- app/controllers/assessments_controller.rb
- app/models/need.rb
- app/views/assessments/new.html.erb
- app/views/contacts/_form_fields.html.erb
- app/views/shared/_profile-accordion-edit.html.erb
- app/views/shared/_profile-accordion.html.erb
- config/locales/en.yml
- spec/controllers/assessments_controller_spec.rb
- spec/factories/needs.rb
Fixes 3 simple UI issues:
- nhs number should be NHS number
- Show consents on profile 
- Assessment Errors validations
> 467 nhs number should be nhs number

- app/controllers/passwordless/sessions_controller.rb
- app/models/user.rb
> 412 last logged in date not shown in list of users

- app/assets/stylesheets/bulk-actions.scss
- app/assets/stylesheets/filters.scss
Background:
https://trello.com/c/QedVprNS/463-minor-alignment-of-filters
Solution:
- Adjusted media query values
> Alignment of filters

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/contacts/index.html.erb
- app/views/shared/_mini-search.html.erb
- app/views/users/index.html.erb
- features/search_user.feature
- features/step_definitions/user_steps.rb
Task: https://trello.com/c/Tdak7rKH/90-add-search-to-users
> Add search to users

- app/controllers/triage_controller.rb
- app/views/contacts/_form_fields.html.erb
- app/views/shared/_profile-accordion-edit.html.erb
- app/views/triage/edit.html.erb
Fix several checkboxes in the triage form
Fix styling in triage form
> 93 consent checkbox bug not appearing on profile after user has entered data into it

- app/controllers/needs_controller.rb
- app/javascript/packs/bulk-actions.js
- app/models/need.rb
- app/views/needs/_bulk-actions.erb
Task: https://trello.com/c/tW6HfDQp/22-quick-update-the-status-of-multiple-needs-use-case-food
> Change category need ad s bulk action

- app/javascript/packs/needs-accordion.js
- app/views/triage/edit.html.erb
- features/on_call_with_resident.feature
- features/step_definitions/person_steps.rb
Task: https://trello.com/c/TaPC89Uz/105-triage-need-with-details-but-no-tick-does-not-record-data
Thanks to @riccardo-noviello-contractor for fixing cucumber tests.
> Need accordion

- app/controllers/needs_controller.rb
- app/views/needs/_bulk-actions.erb
- app/views/needs/_need-actions.html.erb
Task: https://trello.com/c/3HyZQ8eE/43-assign-to-me-quick-action
> Assign to me quick action

- app/controllers/needs_controller.rb
- app/javascript/packs/bulk-actions.js
- app/models/need.rb
- app/policies/need_policy.rb
- app/views/needs/_bulk-actions.erb
- config/routes.rb
Task: https://trello.com/c/tW6HfDQp/22-quick-update-the-status-of-multiple-needs-use-case-food
> Add need bulk action set status

- app/assets/stylesheets/table.scss
- app/controllers/contacts_controller.rb
- app/controllers/needs_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/views/needs/_filters.html.erb
- app/views/users/index.html.erb
- db/migrate/20200512080658_add_deleted_at_to_users.rb
- db/schema.rb
- features/step_definitions/user_roles_steps.rb
- spec/controllers/needs_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/models/user_spec.rb
> 14 deactivate users

- app/models/need.rb
Task: https://trello.com/c/1OVPhFL8/107-add-new-need-types-to-triage
> Add new needs categories

- app/assets/stylesheets/accordion.scss
- app/assets/stylesheets/content-header.scss
- app/assets/stylesheets/forms.scss
- app/assets/stylesheets/need.scss
- app/controllers/contacts_controller.rb
- app/controllers/triage_controller.rb
- app/javascript/packs/accordion.js
- app/javascript/packs/users_viewing_page.js
- app/views/assessments/new.html.erb
- app/views/contacts/edit.html.erb
- app/views/contacts/edit.js.erb
- app/views/contacts/show.html.erb
- app/views/contacts/show.js.erb
- app/views/contacts/update.js.erb
- app/views/layouts/application.html.erb
- app/views/needs/show.html.erb
- app/views/shared/_lead_service_panel.html.erb
- app/views/shared/_profile-accordion-edit.html.erb
- app/views/shared/_profile-accordion.html.erb
- app/views/shared/_profile-errors.html.erb
- app/views/shared/_side-contact-profile.html.erb
- app/views/shared/_side-nav.html.erb
- app/views/triage/edit.html.erb
- features/on_call_with_resident.feature
- features/step_definitions/permissions/permissions_contacts_steps.rb
- features/step_definitions/person_steps.rb
- features/step_definitions/user_steps.rb
- features/support/ajax_edit_helper.rb
- features/update_resident.feature
OK - Check users viewing page works from (contact, needs, triage)
OK - Check edit contact works from (contact, needs, triage)
OK - Check accordion works from (contact, needs, triage)
OK - Check edit contact saves from (contact, needs, triage)
OK - Check edit contact validation messages (contact, needs, triage)
OK - Check Select2 still works
> Saving contact form with Ajax

- app/javascript/packs/needs-index.js
- app/views/shared/_side-nav.html.erb
Task: https://trello.com/c/cK3xb7XR/152-new-in-progress-navigation
> New navigation all needs In Progress

- .rubocop.yml
- app/controllers/needs_controller.rb
- app/controllers/needs_table_controller.rb
- app/models/need.rb
- app/views/shared/_side-nav.html.erb
- app/views/shared/table/_filters.html.erb
Task: https://trello.com/c/jhHRiwsS/155-needs-nav-future-triages-and-check-ins
> Needs future navigation

- app/views/shared/_side-nav.html.erb
Task: https://trello.com/c/uwv0iTxM/160-agents-should-still-see-my-dashboard-which-should-be-anything-assigned-to-them
> Agents should still see 'My dashboard'

- app/javascript/packs/bulk-actions.js
> fix bulk action js file

- app/assets/stylesheets/need.scss
Background:
https://trello.com/c/TkFITS7L/173-styling-inconsistency
Solution:
- Made both Start Check-in and Start Triage button the same width
> Styling inconsistency

- app/assets/stylesheets/need-accents.scss
Background:
https://trello.com/c/TdgX3xl8/180-colours-for-new-need-categories
Solution:
- added class styling for the new need categories
> Colours for new need categories

- app/controllers/assessments_controller.rb
- app/models/assessment_assignment_form.rb
- app/views/assessments/assign.html.erb
Task: https://trello.com/c/weYyRXcw/185-add-change-status-dropdown-to-the-assessment-flow-assign-step
> Add 'Change Status' dropdown to the assessment flow - Assign step

- app/views/shared/_side-nav.html.erb
- features/step_definitions/user_roles_steps.rb
Background:
https://trello.com/c/aYoLWdFn/181-manager-navigation-panel
Solution:
- Made the in progress and future sub menu links
> Manager navigation panel

- app/assets/stylesheets/assessment.scss
- app/assets/stylesheets/progress-wizard.scss
- app/views/assessments/_groceries_and_cooked_meals.html.erb
- app/views/assessments/complete.html.erb
- app/views/assessments/edit.html.erb
- app/views/assessments/fail.html.erb
Background:
https://trello.com/c/0ME4wbgI/177-different-font-sizes-between-contact-panel-and-assessment-flow-looks-strange
Solution:
- Introduced more specific assessment css classes where needed. Also increased bottom margin of progress wizard
> Different font sizes between Contact panel and assessment flow looks strange

- app/controllers/assessments_controller.rb
- app/models/assessment_completion_form.rb
- app/views/assessments/complete.html.erb
- features/step_definitions/assessments/complete_assessment_steps.rb
Background:
https://trello.com/c/3bKQYvzC/171-add-description-text-to-explain-purpose-of-call-back-on-complete-assessment-page
Solution:
- Added description text area to the assessment completion form
> Added description when scheduling next check-in call

- app/assets/stylesheets/need.scss
- app/helpers/needs_helper.rb
- app/javascript/packs/accordion.js
- app/views/assessments/_need-item.erb
- app/views/assessments/edit.html.erb
Background:
https://trello.com/c/CicTe7l1/179-not-a-priority-more-needs-concept
Solution:
- Introduced an accordion on the triage assessment page
> Place not more uncommon needs inside an accordion

- app/views/mdt/index.html.erb
1. Change the MDT Dashboard table categories section to the description field (when agents add description when  assigning that person to MDT Reviews)
2. Change the button from Action to View Profile
Task: https://trello.com/c/aAfUXbfH/191-mdt-dashboard
> MDT DASHBOARD

- app/models/contact.rb
- app/views/contacts/index.html.erb
- features/search_person.feature
- features/step_definitions/person_steps.rb
> Fix search function

- db/seeds.rb
- lib/tasks/add_contact_camden_role.rake
You should run the rake on production:
`bundle exec rake update:create_contact_camden_role`
> Add Contact Camden team

- Gemfile
- Gemfile.lock
- app/controllers/imported_items_controller.rb
- app/models/imported_item.rb
- lib/errors.rb
I reworked the existing import. Please take a look at how we show duplicated records error. I can also add new column in needs section(s) to show the name of the import to allow bulk actions on that needs.
You should also run `bundle install`, because I added new gem for xlsx.
> Rework existing export

- app/assets/stylesheets/forms.scss
- app/views/contacts/_extra_question_household.html.erb
- app/views/contacts/_extra_questions.html.erb
- app/views/contacts/_form_fields.html.erb
I tried to avoid rewriting the CSS and instead moved the markup around a little bit. It's probably not as good as making a better generic form style but it seems to work for now. 
Trello https://trello.com/c/8c1MYh2H/68-fix-alignment-of-some-fields-on-new-contact-form
> 68 Fixes alignment issues on chrome

- app/models/imported_item.rb
Include DOB as part of rejection validation criteria
[Trello 91](https://trello.com/c/5C483seG/91-include-dob-in-name-check-for-data-import)
> Add the DOB to the name for duplicates checking

- app/views/imported_items/index.html.erb
[Trello card](https://trello.com/c/mvy6n8gA/107-display-import-stats-for-successful-and-rejected-data-on-the-imported-items-screen)
> Display the imported item successes and rejections

- app/views/needs/_notes.html.erb
From discussion today in Sprint Planning
Old format
> Update date format for notes

- app/views/contacts/_imported_item_contacts.html.erb
- app/views/contacts/index.html.erb
Move imported contacts table into separate partial and continue to use old table for main contacts view.
> Move imported contacts table into separate partial 

- app/assets/stylesheets/_layout.scss
- app/assets/stylesheets/contacts.scss
- app/models/contact.rb
- app/views/shared/_profile-accordion.html.erb
- app/views/shared/_vulnerable-banner.html.erb
- spec/models/contact_spec.rb
- spec/rails_helper.rb
[73-highlight-under-18s-in-contacts](https://trello.com/c/3Qi9eYJI/73-highlight-under-18s-in-contacts)
Shows user when a contact is Under 18
> Trello-73: Highlight under 18's in contacts

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
Bit messy but easiest solution I could think of for now. We couldnt use Rails.env as this is procutoin on staging environment. Would rather not change that as think its good for staging to be as close to prod as possible
> Use env hostname to determine env

- app/views/needs/index.html.erb
Reverts wearefuturegov/beacon#393
> Revert "Trello-126: - Allow ordering of needs based on 'assigned to'"

- app/controllers/contacts_controller.rb
You still end up in search action if you clear search. Slgihtly odd but more complex to change as mini-search partial uses url param and is shared by other sections of app. This is simplest fix for now and given time constraints best approahc
> Only search if param present. 

- app/assets/stylesheets/mini-search.scss
- app/views/shared/_mini-search.html.erb
[Better search assistance for user](https://trello.com/c/izwboFZv/70-search-label)
> Trello-70: Add more detailed description of what fields can be searched

- app/controllers/contacts_controller.rb
Just tested on staging and seems to have fixed the bug
https://trello.com/c/oEmzgGOU/148-search-for-contact-test-on-staging-bug
> Search bug on staging

- app/views/contacts/_imported_item_contacts.html.erb
Iceboxing - [](https://trello.com/c/g6cSBOEB/130-import-category-column-not-being-populated)
[This ticket](https://trello.com/c/7am5uO1b/138-too-many-columns)
Also combined with [129-reason-for-failure-not-visible](https://trello.com/c/xQuDMaCr/129-reason-for-failure-not-visible)
**Before**:
**After**:
**Test file**:
[20210112-084100-test-and-trace.xlsx](https://github.com/wearefuturegov/beacon/files/5801117/20210112-084100-test-and-trace.xlsx)
> Trello-138: Reduce number of columns displayed in Import

- DOCKER-README.md
- README.md
- Not Docker 101
- some basic commands
- some links for further exploration
> Add documentation on how to use docker for Beacon

- app/views/shared/_side-nav.html.erb
- features/step_definitions/user_roles_steps.rb
Closes [Trello 153](https://trello.com/c/f2zNp3Kl/153-update-menu-items)
> Adds 'Calls' changes to navigation

- app/helpers/contacts_helper.rb
- app/views/contacts/_form_fields.html.erb
- db/schema.rb
References [Trello ticket 165](https://trello.com/c/zT0LciP2/165-small-improvement-update-names-to-always-be-lowercase-with-capitalised-first-letters)
> Titleize names in contact edit view

- app/models/need.rb
- app/views/needs/index.html.erb
- features/list_support_actions.feature
- features/step_definitions/support_actions_list_steps.rb
References [Trello ticket 179](https://trello.com/b/q3OrgroV/camden-beacon-enhancements)
> Removes call attempts column

- app/models/note.rb
References [Trello issue 183](https://trello.com/c/OcVBdZq5/183-add-some-new-categories)
> Adds additional categories

- app/models/contact.rb
- spec/models/contact_spec.rb
References [Trello issue 166](https://trello.com/c/kqHPPAOS/166-small-improvement-0-on-the-start-of-phone-numbers)
> Fixes bug with adding zero to nil phone fields

- app/controllers/assessments_controller.rb
- app/views/assessments/new.html.erb
- app/views/needs/_notes.html.erb
Addresses issues that @evanschris spotted during testing.
- Adds note categories when creating a call
- Fixes visual bug in Chrome
https://trello.com/c/MlOtjTek/156-changes-to-log-call-screen
> Adds note categories when creating a new log

- app/assets/stylesheets/table.scss
- app/controllers/contacts_controller.rb
- app/views/contacts/_assessment_row.html.erb
- app/views/contacts/_assessments.html.erb
- app/views/contacts/show.html.erb
- features/assessment.feature
- features/assessments/complete_assessment.feature
- features/step_definitions/assessment_steps.rb
- features/step_definitions/assessments/complete_assessment_steps.rb
- features/step_definitions/edit_support_actions_steps.rb
- features/step_definitions/permissions/permissions_support_actions_steps.rb
- features/step_definitions/person_steps.rb
Closes [update person page to reflect new flow](https://trello.com/c/kHiNUn2a/181-update-person-page-to-reflect-new-flow) (not all acceptance criteria were achieved, those that weren't are being moved into new tickets).
> Updates contact page

- app/models/note.rb
- features/create_note.feature
Also standardises casing in menu
> Adds 'Test & Trace Support Payment' as notes category

- app/views/assessments/new.html.erb
- features/assessment.feature
- features/step_definitions/assessment_steps.rb
https://trello.com/c/Xz75PXYr/189-change-submit-button-text-on-schedule-page-to-schedule-call
> Reword schedule call save button

- app/models/contact.rb
- features/search_person.feature
Enabling users to search regardless of space characters in strings
> Postcode search ignores space
