wearefuturegov/beacon

.gitignore
Gemfile
Gemfile.lock
README.md
config/environments/production.rb
config/initializers/sendgrid.rb

instructions followed: https://github.com/ryu39/sendgrid_actionmailer_adapter
a `SENDGRID_API_KEY` variable has been added to the staging and production apps.

use sendgrid to send emails in production

---

app/controllers/contacts_controller.rb
app/helpers/tasks_helper.rb
app/models/contact.rb
app/models/task.rb
app/views/contacts/_form.html.erb
app/views/contacts/index.html.erb
app/views/contacts/show.html.erb
app/views/shared/_tasks_table.html.erb
app/views/tasks/edit.html.erb
app/views/tasks/show.html.erb
db/migrate/20200331192200_remove_priority_from_contact.rb
db/schema.rb
spec/factories/contacts.rb
spec/models/contact_spec.rb

The figma screens seem to use a boolean 'is vulnerable' rather than a 3-tier priority, so I've updated things to reflect that. @jhackett1 this still needs some styling when you have a sec.
Technically this field already existed on the model so we simply dropped the old priority field and started using is_vulnerable.
I also modified the seed factory from 100% true to 30% true.
@jamiebuckley started on similar radio buttons in #33 so may be able to share styling.

Use is_vulnerable instead of priority on contacts

---

app/views/contacts/index.html.erb

This PR implements:
- Remove "Assigned" column from people list (needs are assigned; not people)
- Emphasise count of incomplete tasks on people list. Shows count of completed tasks, if any, next to it. If no tasks exist, doesn't show anything. (previously this showed the total count of tasks and the number of completed tasks).

Improve people list ui

---

app/controllers/needs_controller.rb
app/helpers/needs_helper.rb
app/models/need.rb
app/views/needs/show.html.erb
app/views/shared/_needs_table.html.erb

Search is case sensitive.  Categories are converted to snake_case and then humanized again, so 'Staying Social' becomes 'Staying social'.
This makes sure that categories are inserted into the db in lower case, but keeps the display of the categories as is

Ensure categories are inserted in lower case

---

app/views/passwordless/mailer/magic_link.html.erb
app/views/user_sign_in_mailer/send_invite_email.html.erb

This is rendered as a relative URL; a full URL is needed for emails, including the hostname. We could get around that by using `ENV['MAILER_URL']` with an `https://` prefix,but rails docs recommend this way: https://guides.rubyonrails.org/action_mailer_basics.html#adding-images-in-action-mailer-views
Removing it in the meantime as having a broken image probably isn't helping our spam score 😬
@jhackett1 if you're up for getting the logo to work, feel free to close this PR. Just thought we'd do this in the meantime.

Remove broken logo from emails

---

.github/workflows/run_spec_tests.yml

Per #75, [this comment](https://github.com/rspec/rspec-rails/issues/208#issuecomment-413114), and [usage docs](https://github.com/rspec/rspec-rails#running-specs). With the caveat that maybe there was a reason `rails spec` was used that I'm not aware of. I defer to @rubyforbusiness

Use rspec instead of rails spec in CI

---

Gemfile
README.md
app.json
app/views/user_sign_in_mailer/send_invite_email.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
db/seeds.rb
spec/mailers/user_sign_in_mailer_spec.rb
spec/rails_helper.rb

This will allow us to run `db:seed` in production without loading factorbot+faker when the server runs, and that command will seed the users table with any emails specified in the env var. And the hostnames in emails will work on review apps.
Just need to add a command to the heroku config so that review apps run `db:seed` when they're created, but that can be a separate PR.

Support review apps

---

app/controllers/application_controller.rb

**Background**
We are using login and after logging in, there's a flash that says "Please sign in" which is wrong.
**Aim**
Remove wrong flash that says "Please sign in" after login.
**Implementation**
Remove the `flash` in `redirect_to`.
**TIL**
We are using `passwordless` gem to create and manipulate the magic link.
In gem [example](https://github.com/mikker/passwordless#getting-the-current-user-restricting-access-the-usual) we see:
```
redirect_to root_path, flash: { error: 'You are not worthy!' }
```
In this case we will `flash` message in all cases, whether we were successful with the authentication or not. 
Actually if using wrong link we will `raise` exception. Example `/sign_in/wrong_link`.
But if we are not sign in and try `/contacts` we will be redirected to `/sign_in` with …

Remove wrong flash sign in message

---

app/assets/stylesheets/filters.scss

Background:
https://trello.com/c/SleQd7i2/295-fix-styling-of-filters-on-narrower-screens
Solution:
- Supported flex container growing thus preventing horizontal overflow

Prevented filters section horizontal overflow

---

app/assets/stylesheets/forms.scss
app/views/needs/_notes.html.erb

Background:
https://trello.com/c/d9DEFBuW/290-improve-styling-of-note-category-control-and-display
Solution:
- Arranged radio buttons horizontally in a grid row
- Made the node type bold

Improve styling of note category control and display

---

app/assets/stylesheets/accordion.scss
app/javascript/packs/accordion.js
app/views/shared/_profile-accordion.html.erb

Background:
https://trello.com/c/Js7GZBxK/307-ie-11-bug-accordions-not-closing
Solution:
- As it turned out, IE11 **doesn't support forEach** method on NodeList, which is retuend by **querySelectorAll**. Converting the NodeList to Array solves the problem.
- Expanded all accordions when loading the contacts view

IE11 accordion expansion/closing doesn't work

---

app/models/need.rb
app/services/needs_creator.rb
app/views/needs/show.html.erb
app/views/triage/_groceries_and_cooked_meals.html.erb
db/migrate/20200415112940_add_supplemental_data_to_needs.rb
db/schema.rb

**Note: This PR is meant to be merged into @jamiebuckley's branch**
This commit also consolidates the two dietary requirements questions. I've added validation for the two new need fields, but commented it out until we get validation working in the triage controller.

Add supplemental fields to food need

---

app/views/contacts/_extra_questions.html.erb

Background:
https://trello.com/c/mnaH4m1Q/318-radio-buttons-not-properly-aligned
Solution:
- Removed extra <br /> tags which caused the radio button divs to be placed on separate lines

Radio buttons not properly aligned

---

app/models/need.rb

This is based on the list of fields the food delivery team expects. I switched to using a hash so we could control the field names.
(Note this is branched off of #134)

Add fields to needs export

---

app/views/contacts/_extra_questions.html.erb

I expect managers may be filling out this form without always having this infromation to hand. This validation made it so you can't submit the form without a number.

Remove validation from count_people_in_house

---

app/controllers/needs_controller.rb
app/models/need.rb
features/list_needs.feature
features/step_definitions/need_steps.rb
features/step_definitions/needs_list_steps.rb
features/step_definitions/person_steps.rb
spec/controllers/needs_controller_spec.rb

Prior to this, the needs index showed needs that hadn't started yet, and didn't differentiate them. Ideally we'd indicate it in a column and enable filtering on it, but that's quite complex. This is a short-term fix. You can still view future needs on the person page.

Hide future needs on needs index

---

spec/models/need_spec.rb

Explanation:
'Started' needs were built like this
```
let!(:created_tomorrow_started) { build :need, name: 'created tomorrow, no start date', created_at: DateTime.now + 1.days }
```
Which meant that whether or not those needs had a start date was decided by factorybot via:
```
start_on { [nil, Faker::Date.between(from: 2.days.ago, to: 6.days.from_now)].sample }
```

Ensure Needs with no start date built via factorybot have nil start_on

---

app/assets/stylesheets/_globals.scss
app/assets/stylesheets/forms.scss
app/assets/stylesheets/mini-search.scss

Background:
https://trello.com/c/WVVMmJfY/308-ie-11-concerns
Solution:
- An extra arrow was appearing on IE 11 select boxes. Added the required pseudo-class to hide it.
- Added required vendor prefixes to style placeholders across different browsers

Fixed IE 11 select boxes and placeholder styling conerns

---

app/views/needs/show.html.erb

This allows for line breaks in need descriptions (the `name` field), which are now needed because the re-import has a ton of them. I've tested this in staging.

Hotfix: use simple_format in need name/description

---

app/assets/stylesheets/content-header.scss
app/assets/stylesheets/nav.scss
app/assets/stylesheets/need.scss
app/assets/stylesheets/popup.scss
app/javascript/packs/enquiry-common.js
app/views/contacts/show.html.erb
app/views/layouts/application.html.erb
app/views/needs/show.html.erb
app/views/shared/_popup.erb
app/views/shared/_side-nav.html.erb
features/step_definitions/authentication_steps.rb

Background:
https://trello.com/c/TGmpxL1m/359-12-quick-capture-referral
Solution: 
- Moved name and sign out at the bottom left
- Moved Triage button above the needs table
- Moved the Add Enquiry button at the top right corner

12. Quick capture referral Design 

---

app/assets/stylesheets/nav.scss

Background:
https://trello.com/c/efvDD3b4/408-user-name-overflowing-navigation-menu
Solution:
The bottom section is now responsible, so it can accommodate for different screen sizes. Also, the user name spans over multiple lines, if needed.

User name overflowing navigation menu

---

README.md
app/assets/stylesheets/_layout.scss
app/assets/stylesheets/need-accents.scss
app/assets/stylesheets/table.scss
app/assets/stylesheets/triage.scss
app/controllers/triage_controller.rb
app/helpers/needs_helper.rb
app/models/need.rb
app/validators/contact_needs_validator.rb
app/views/contacts/_needs-table.html.erb
app/views/contacts/show.html.erb
app/views/needs/_filters.html.erb
app/views/needs/index.html.erb
app/views/needs/show.html.erb
app/views/triage/edit.html.erb
features/list_needs.feature
features/step_definitions/edit_need_steps.rb
features/step_definitions/needs_list_steps.rb
features/step_definitions/permissions/permissions_search_steps.rb
features/step_definitions/permissions/permissions_steps.rb
spec/factories/needs.rb
spec/helpers/needs_helper_spec.rb

This refactor uses an enum for `category` in the need model, which simplifies working with the list of categories a bit.
Significantly, it moves the border/stroke colours to CSS. This involves hard-coding categories in CSS classes. I considered simply having a CSS variable that was a list of colours, and the stroke colour would be based on the index in the enum. That would probably be better but might be a bit less obvious what's going on, so this seemed fine. I could go either way though.
I've got some failing cucumber tests, and I _think_ it may be because of some of my refactoring in the triage controller. In particular, I'm not sure what `merge_contact_needs` was meant to do or if we still need it now that colours aren't involved in the list. @jamiebuckley can you take a peek when you …

Refactor: Use enum for need category

---

app/views/triage/edit.html.erb

Background:
https://trello.com/c/zk5jLVKB/403-misc-triage-form-should-have-the-profile-accordion-alongside-it
Solution:
Added the profile accordion on the left hand side.

Added profile accordion to triage form

---

lib/tasks/users_roles.rake

Data migration rake to:
- create all roles for the live database 
- assign existing users to appropriate roles based on admin flag
Task: https://trello.com/c/gIxrZRCI/365-data-migration-task-to-create-all-roles-for-the-live-database-and-assign-existing-users-to-appropriate-roles
First create the roles:
```
bundle exec rake users_roles:create_roles
```
After that assign role to user:
```
bundle exec rake users_roles:assign_roles
```

Create users roles rake tasks

---

app/javascript/packs/contact-form-navigation-alert.js
app/views/contacts/_form.html.erb
app/views/contacts/edit.html.erb
app/views/contacts/new.html.erb

Background:
https://trello.com/c/3BZgNJez/428-warn-users-if-theyre-leaving-the-create-edit-contact-page-with-unsaved-changes
Solution: 
- I use the "onbeforeunload" event. Since rails turbo links prevent full page reload, I disable them only on the page where the warning is needed. After we leave the page, they are restored.

Warn users if they’re leaving the create/edit contact page with unsaved changes

---

app/assets/stylesheets/_globals.scss
app/assets/stylesheets/bulk-actions.scss
app/views/needs/_bulk-actions.erb
app/views/needs/index.html.erb

Background:
https://trello.com/c/jUyj4aiB/436-move-export-and-filter-buttons-to-the-right-above-the-table
Solution:
- Moved export and filter buttons to  the right, above the temple.
- Since text-overflow doesn't seem to work correctly on select element, except for Firefox, I made the roles assignment boxes wider, so not to clip the displayed text.

Move export and filter buttons to the right, above the table

---

README.md
app/views/shared/_head.html.erb

This PR removes Google Tag Manager since we don't expect this to be managed and it's otherwise a big vector. In its place, it leaves the [google analytics snippet](https://developers.google.com/analytics/devguides/collection/analyticsjs/) and makes the whole thing optional.

Replace Google Tag Manager with Google Analytics and make it optional

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/assessment.scss
app/javascript/packs/assessments.js
app/views/contacts/show.html.erb
features/step_definitions/assessment_steps.rb

Background:
https://trello.com/c/Y51nfQC5/439-make-the-add-assessment-button-a-dropdown-like-the-designs
Solution:

Make the 'add assessment' button a dropdown like the designs

---

app/services/needs_creator.rb
db/migrate/20200501095215_set_default_status_on_needs.rb
db/schema.rb

Fixes bug where Other needs were not showing on a contacts profile because they had a NULL status

Set status of "Other" needs, and set default status in DB

---

app/javascript/packs/bulk-actions.js
app/views/needs/_bulk-actions.erb

Background:
https://trello.com/c/zSdkJ9Go/447-assignment-usability
Solution:
- When the assign to select box is rendered, it has initially the disabled attribute applied to it.
- When the user manipulates a need checkbox, the select box will be enabled/disabled based on the count of checked needs.
- When a user un-checks all check boxes, the Assign All check box get un-checked as well.

Assignment usability

---

app/models/need.rb
app/policies/need_policy.rb

An explanation of the issue:
There are three 'mutations' of the active record query that get performed.
1. The policy scope, which limits the records a user can see to those assigned to the right teams/users
2. The aggregations, which add extra calculated fields from subqueries
3. The filter/sort
Given that there is a fairly complex interplay between these queries, the simplest solution is to take the policy queries, and move them into a `where in (subquery)` query.  This means that the sorting issues - caused by a mismatch of distinct/aggregate columns, should be fixed, and the overall SQL structure is easier to understand.

BugFix: Food manager receives error

---

app/controllers/contacts_controller.rb
app/controllers/triage_controller.rb
app/views/contacts/_extra_questions.html.erb
app/views/shared/_profile-accordion-edit.html.erb
app/views/shared/_profile-accordion.html.erb
db/migrate/20200504123442_rename_fifteen_to_age_contacts.rb
db/schema.rb
features/step_definitions/person_steps.rb
spec/factories/contacts.rb

Background:
https://trello.com/c/0xiu8v2U/81-change-are-there-any-children-under-15-living-in-the-household-to-are-there-any-children-under-18-living-in-the-household
Solution:
- Renamed labels in the UI, variables in the back-end and table column.

Change 'Are there any children under 15 living in the household?' to 'Are there any children under 18 living in the household?"

---

app/views/triage/_groceries_and_cooked_meals.html.erb

Background:
https://trello.com/c/YKsWJNH3/82-remove-priority-3-as-an-option-for-food-priorty
Solution:
- Removed the priority 3 radio button
- Need to create cleanup script for Priority 3 needs in the db

Remove 'Priority 3' as an option for food priority

---

app/javascript/packs/completed-needs.js

When we dont have completed needs we dont have element for them. In this case we can not add event listener to the element.

Fix completed needs js error

---

app/assets/stylesheets/forms.scss
app/views/assessments/_groceries_and_cooked_meals.html.erb
app/views/assessments/_prescription_pickups.html.erb
app/views/assessments/complete.html.erb
app/views/assessments/fail.html.erb
app/views/needs/_notes.html.erb

Background:
https://trello.com/c/Uqpfsa8x/169-make-radio-buttons-slightly-smaller-space-between-options
Solution:
- Introduced another css class for smaller radio buttons.

Make radio buttons slightly smaller

---

app/assets/stylesheets/pagination.scss
app/helpers/application_helper.rb
app/javascript/packs/pagination.js
app/views/shared/_pagination.html.erb

Background:
https://trello.com/b/UE2qyYpg/beacon-platform-4th-may-3rd-june
Solution:
- Added a text field for entering a page number and a link next to it, to perform the navigation.
If the field is empty or contains invalid input, the link is disabled.

Added Go to page functionality

---

app/views/assessments/complete.html.erb
features/step_definitions/assessments/complete_assessment_steps.rb

Task: https://trello.com/c/I7FmwXcA/172-remove-assessment-from-assessment-completion-final-submit-button-should-just-say-complete

Change 'complete assessment' to 'complete'

---

.github/workflows/run_spec_tests.yml
Dockerfile.dev
README.md
config/database.yml
config/environments/development.rb
config/webpacker.yml
docker-compose.yml
entrypoint.sh

This ought to work for local / docker-compose development now. The only thing I needed to change was turn off yarn integrity check in the test environment, seemed like an ok-ish workaround for now.

Containerising the app for development

---

app/models/concerns/clean_data.rb
app/models/contact.rb
spec/models/contact_spec.rb

This is to prevent future duplicates entering the system via user input on the `Add person form`
`Mark     ` will become `Mark`
A separate PR will be rasied to clean existing data

Strip whitespace from all AR attributes that respond_to strip - Contacts model

---

docker-compose.yml

Tiny fix so that magic links change in the logs in development to be usable
Prior to this fix in docker we got:
```
This is a GOV.UK Notify email with template 47da4e5d-ef0d-4ab7-91ee-eb96baa4ed07 and personalisation: {:magic_link=>"http://87dcf0846660/sign_in/zgZvApDer6KScN-H9RGYdcB9vnHlXoEtZwi2gwGsMkY", :timeout=>60}
```
With this fix will get:
```
This is a GOV.UK Notify email with template 47da4e5d-ef0d-4ab7-91ee-eb96baa4ed07 and personalisation: {:magic_link=>"http://localhost:3000/sign_in/bxK3E0DU3DCu-emCtpi1dnsdMihE98rwWWc4Y3q-_EY", :timeout=>60}
```

Make magic links work on docker (development)

---

app/controllers/imported_items_controller.rb
app/models/imported_item.rb
db/migrate/20201215112311_add_test_trace_creation_date_and_isolation_start_date_to_contacts.rb
db/schema.rb

Add additional fields from import spreadsheet
- `test_trace_creation_date`
- `isolation_start_date`
Some minor refactoring to names in import method as `row` did not feel right in all places referenced
Move Rails.logger.unknown message about `User imported new contacts` to after Rollback, as if Rollback occurs then technically zero new records are imported
```ruby
[1] pry(main)> Contact.last
Contact Load (0.4ms)  SELECT "contacts".* FROM "contacts" ORDER BY "contacts"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<Contact:0x00007f7878a037d0
id: 639,
first_name: "Casey",
middle_names: nil,
surname: "Addams",
address: "201 White Shires Road",
postcode: "N1 0AB",
telephone: nil,
mobile: "+44762",
gds_import_data: nil,
is_vulnerable: false,
created_at: Tue, 15 Dec 2020 15:45:45 UTC +00:00, …
```

Add 2 additional fields to data import

---

app/controllers/contacts_controller.rb
app/models/contact.rb
app/views/contacts/_form_fields.html.erb
app/views/shared/_profile-accordion-edit.html.erb
app/views/shared/_profile-accordion.html.erb
config/locales/en.yml

- test_trace_creation_date
- isolation_start_date
Also display on relevant pages
[Trello 106](https://trello.com/c/hijZDsyB/106-add-new-fields-to-new-edit-forms-for-contacts)

Allow manual input of new contact form fields 

---

app/models/imported_item.rb

[Trello 110](https://trello.com/c/X5K1YiQW/110-import-starts-on-date-needs-to-be-the-day-of-import-rather-than-2-days-time)
Used this as test data
[20201216-123600-test-and-trace.xlsx](https://github.com/wearefuturegov/beacon/files/5709666/20201216-123600-test-and-trace.xlsx)
Row 7 - Natalia is used for an import with the old calculation of `today + 2.days`
Row 8 - Dave is used for the import where the Need `start_date = today`
You can also see that the source for these has changed to reflect discussion in todays meeting of the Note.name becoming `National Test and Trace Outbound Welfare Call`

Change the start date of a need to be todays date

---

Gemfile.lock

As noted in the dependabot issues.

Update rack gem to address CVE-2020-8184

---

app/assets/stylesheets/_layout.scss
app/assets/stylesheets/_variables.scss
app/views/layouts/application.html.erb

Does what it says on the tin! But not quite as originally requested. 
see [102-staging-banner](https://trello.com/c/bxve5vZq/102-staging-banner)

Trello-102: Staging Banner

---

app/views/needs/index.html.erb

[Trello #126 - Sort Needs by 'assigned to' column](https://trello.com/c/uL8qhu1a/126-request)
Example screenshots of solution

Trello-126: - Allow ordering of needs based on 'assigned to'

---

app/controllers/contacts_controller.rb
app/views/contacts/_form_fields.html.erb
app/views/shared/_profile-accordion-edit.html.erb
app/views/shared/_profile-accordion.html.erb
db/migrate/20210106132742_add_business_name_to_contacts.rb
db/schema.rb
features/new_person.feature
features/step_definitions/new_person_steps.rb
features/step_definitions/person_steps.rb
features/update_resident.feature

[Trello-114](https://trello.com/c/ilRqzfSQ/114-add-ability-to-add-a-business-rather-than-a-person-for-inbound-calls-eg-surname-business)
Added for speed using the old sytling, as it will take a bit longer to build the entire form with the new styles.

114 - Add ability to add a business for inbound calls

---

app/controllers/imported_items_controller.rb
app/views/imported_items/index.html.erb

[Default sort ordered by most recent imports](https://trello.com/c/gKMTgfCZ/131-sort-by-most-recent-first-post-import)
Also added 'N/A' where no data available for `Imported`, `Rejected` and `Imported By`

Trello-131: default sort order is by created_at DESC, N/A when no results

---

app/models/concerns/name_formatter.rb
app/models/contact.rb
app/models/user.rb
spec/models/contact_spec.rb
spec/models/user_spec.rb

Closes https://trello.com/c/zT0LciP2/165-small-improvement-update-names-to-always-be-lowercase-with-capitalised-first-letters

Titleizes names of contacts and users

---

app/helpers/contacts_helper.rb
app/views/contacts/_imported_item_contacts.html.erb
app/views/contacts/index.html.erb
app/views/shared/_profile-accordion-edit.html.erb
app/views/shared/_profile-accordion.html.erb

Closes [Trello 164](https://trello.com/c/trEZv0pz/164-small-improvement-change-the-date-of-birth-day-month-year-to-be-dd-mm-yyyy-throughout)
I just used the default time formatter in the config folder (`config/initializers/time_formats.rb`)

Uses default time formatter for visual DOB

---

app/views/shared/_side-nav.html.erb

Filtering was limited by future in https://github.com/wearefuturegov/beacon/pull/418, this shows everything as long as it is has a status of complete.

Lists needs by all times

---

app/models/contact.rb
db/migrate/20210520091922_update_telephone_prepended_zero_contacts.rb
spec/models/contact_spec.rb

Closes [Trello issue #166](https://trello.com/c/kqHPPAOS/166-small-improvement-0-on-the-start-of-phone-numbers)
If a telephone or mobile number does not have a zero or plus at the
start it will have a zero prepended. All existing numbers in the
database are checked and updated with a zero at the beginning if none
exists.

Prepends 0 to contact phone numbers when not there

---

app/controllers/assessments_controller.rb
app/views/assessments/new.html.erb
features/assessment.feature
features/list_support_actions.feature
features/step_definitions/assessment_steps.rb
spec/controllers/assessments_controller_spec.rb

From @evanschris 
> When logging a call the first time we want them to be able to add more than one note at a time rather than write all the notes in at once, so when the save button is clicked could we redirect them to the call page itself rather than back to the person's page?
This would mean they could continue to add more notes.
Then the copy changes - could we make the page more similar to the completed page so
change the notes from textarea to input
change the placeholder text to "Additional notes (optional)"
Change the button to "Save update to call"
All addressed in this PR

Redirects assessment to the assessment and standardises note input

---

app/views/needs/_notes.html.erb

ID assumes sequential ordering in the DB, which is not guaranteed
As with #451 - the integration test runners on heroku are currently out of order:
tests passing evidence:

Bug fix: order notes by created_at not ID
